-
  branches:
    only:
      - release
  environment:
    nodejs_version: "6"
    NPM_TOKEN:
      secure: mnzQMx2AChA/e1ZJTd590T7+RVOGXDVkeA73TMRFMc5+kAjwbzLTZNz8PpDFbPpo

  skip_branch_with_pr: true
  before_build:
    - ps: Install-Product node $env:nodejs_version
    - npm install

  build_script:
    - npm run build
    - npm run test
    - echo publish package
    - npm run ci-publish
-
  branches:
    only:
      - master
  environment:
    nodejs_version: "6"

  before_build:
    - ps: Install-Product node $env:nodejs_version
    - npm install

  build_script:
    - npm run build
    - npm run test
